name: Docs

on:
  push:
    branches:
    - main
    paths:
    - docfx_project/**
    - .github/workflows/docs.yml
  pull_request:
    branches:
    - main
    paths:
    - docfx_project/**
    - .github/workflows/docs.yml
  workflow_dispatch:

jobs:
  generate-docs:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup DocFX
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install docfx

    - name: DocFX Build
      working-directory: docfx_project
      run: docfx .\docfx.json
      continue-on-error: false

    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docfx_project/_site
        force_orphan: true
        
